{ ... }:
{
  # Omarchy owns its shell, prompt, terminal defaults, themes, Quickshell,
  # Hyprland, update lifecycle, and system integration. This profile adds no
  # competing declarations for those capabilities.
  home.username = "j_kro";
  home.homeDirectory = "/home/j_kro";
  home.stateVersion = "26.05";

  # Keep the base profile intentionally empty beyond identity and state. Add a
  # feature here only after proving Omarchy does not already provide it.

  # ── Garage S3 (cluster object storage) via rclone ────────────────────────
  # Garage runs on nexus (10.1.1.120:3900). The remote config is generated by
  # upstream Home Manager programs.rclone into ~/.config/rclone/rclone.conf
  # (mode 600). Credentials are injected at activation from the SecretSpec/
  # SOPS-provisioned files via the `secrets` option — never written into the
  # world-readable Nix store.
  #
  # Secret path requirement (omarchy target): the files must be readable by
  # the Home Manager user at activation (0600/0440 user-ownable). On the
  # transitional NixOS host they are root:root 0440 under /run/secrets, so
  # the bootstrap must write a user-readable copy before this profile is
  # activated there. See plans/2026-08-20-omarchy-hm-cluster-vision.md
  # ("Secrets and trust bootstrap | Host/bootstrap + SecretSpec/SOPS policy").
  programs.rclone = {
    enable = true;
    remotes = {
      garage = {
        config = {
          type = "s3";
          provider = "Other";
          endpoint = "http://10.1.1.120:3900";
          region = "garage";
          force_path_style = true;
        };
        secrets = {
          access_key_id = "/run/secrets/garage-s3-access-key-id";
          secret_access_key = "/run/secrets/garage-s3-secret-key";
        };
      };
    };
  };

  # Daily verification: list the garage buckets. Fails fast if the endpoint
  # is dead (TimeoutStartSec 300) instead of hanging forever.
  programs.rclone-sync = {
    enable = true;
    syncJobs = [
      {
        name = "garage-list";
        source = "garage:";
        mode = "ls";
        startAt = "03:00";
        enableTimer = true;
      }
    ];
  };
}
